### PR TITLE
Update documentation main page

### PR DESCRIPTION
**Pull request by bmxam**

### CODE REVIEW

**Comment by bmxam** [comment]
@ghislainb  : the gallery on the welcome page (https://bcube-project.github.io/Bcube.jl/previews/PR27/) is not displayed correctly. I don't know why since it's a copy paste from the README. I see two immediate solutions:
* I copy the assets (~png and gif) in the `Bcube/doc`
* I delete the "Gallery" section of this welcome page

**Review by ghislainb — APPROVED** [review]

**Comment by bmxam** [comment]
> @ghislainb : the gallery on the welcome page (https://bcube-project.github.io/Bcube.jl/previews/PR27/) is not displayed correctly. I don't know why since it's a copy paste from the README. I see two immediate solutions:
> 
>     * I copy the assets (~png and gif) in the `Bcube/doc`
> 
>     * I delete the "Gallery" section of this welcome page

@ghislainb , what do you prefer?

**Comment by ghislainb** [comment]
> 
> @ghislainb , what do you prefer?

first option

**Comment by bmxam** [comment]
@ghislainb I finally succeeded in fixing the gallery (except for the vertical alignment). If it's ok for you, I merge (or do it directly)

**Review by ghislainb — APPROVED** [review]

**Pull request merged**
