### PR TITLE
use temporary transposed matrix to set dirichlet BCs

### PR DESCRIPTION
**Pull request by ghislainb**

### CODE REVIEW

**Comment by bmxam** [comment]
According to codecov, this function is not tested. Please wait while I test it on one of my (complicated) problem

**Comment by ghislainb** [comment]
> According to codecov, this function is not tested. Please wait while I test it on one of my (complicated) problem

If the script works as expected, the function is tested with the integration tests in the [heat_equation](https://github.com/bcube-project/BcubeTutorials.jl/blob/98531359b6cb684b197231174a3092bc2872bc79/src/tutorial/heat_equation.jl#L118) tutorial at least. But I will wait for your feedback.

**Comment by bmxam** [comment]
> > According to codecov, this function is not tested. Please wait while I test it on one of my (complicated) problem
> 
> If the script works as expected, the function is tested with the integration tests in the [heat_equation](https://github.com/bcube-project/BcubeTutorials.jl/blob/98531359b6cb684b197231174a3092bc2872bc79/src/tutorial/heat_equation.jl#L118) tutorial at least. But I will wait for your feedback.

I've checked and everything's working fine. But let me write a tiny unit test to improve coverage.

**Review by bmxam — APPROVED** [review]

**Review by lokmanb — APPROVED** [review]
Looks good to me

**Pull request merged**
